version: "3.1"
services:
  web:
    image: "odoo:14.0"
    container_name: odoo_test
    depends_on:
      - db
    ports:
      - "8025:8069"
    volumes:
      - "/mnt/user/appdata/Odoo_Test:/var/lib/odoo"
      - "/mnt/user/appdata/Odoo_Test/config:/etc/odoo"
      - "/mnt/user/appdata/Odoo_Test/addons:/mnt/extra-addons"
    environment:
      - "USER=xushier"
      - "PASSWORD=xushier666"
  db:
    image: "postgres:13"
    container_name: postgresql_odoo
    environment:
      - "POSTGRES_DB=odoo"
      - "POSTGRES_PASSWORD=xushier666"
      - "POSTGRES_USER=xushier"
      - "PGDATA=/var/lib/postgresql/data/pgdata"
    volumes:
      - "/mnt/user/appdata/Odoo_DB_Test:/var/lib/postgresql/data/pgdata"